language: python

python:
  - 2.7.12

services:
  - mysql

env:
  DOCKER_COMPOSE_VERSION: 1.21.0

install:
  - pip install -q django==$DJANGO
  - pip install -q -r requirements.txt
  - docker pull mysql:5.7.14
  - mkdir db
  - docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v /db:/var/lib/mysql  mysql:5.7.14
  - sleep 40
  - >
    docker run -it --name mysql-cmd --link mysql:db mysql:5.7.14 bash
    mysql -uroot -p'$3cureUS' -h db -v -e
    "create user 'www'@'%' identified by '$3cureUS';
    create database cs4501 character set utf8;
    grant all on *.* to 'www'@'%'; "

before_script:
  - docker-compose up -d

script:
  - > 
    docker exec -it models_1 bash -c
    "python app/myapp_microservices/manage.py test"

after_script:
  - docker-compose down
