language: python

python:
  - 2.7.12

services:
  - mysql

env:
  global:
    - DJANGO_SETTINGS_MODULE="myapp_microservices.settings"
    - PYTHONPATH="/home/travis/build/joshmgross/record-marketplace"
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO=1.10 DB=mysql

install:
  - pip install -q django==$DJANGO

before_script:
  - mysql -e 'create database travis_ci_db;'
  - python app/myapp_microservices/manage.py syncdb --noinput

script:
  - python app/myapp_microservices/manage.py test