language: python

python:
  - 2.7.12

services:
  - mysql

env:
  DOCKER_COMPOSE_VERSION: 1.21.0

install:
  - pip install -q django==1.10
  - pip install -q -r requirements.txt
  - docker pull mysql:5.7.14
  - mkdir db
  - docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v /db:/var/lib/mysql  mysql:5.7.14
  - sleep 15
  - docker run -it --name mysql-cmd --link mysql:db mysql:5.7.14 bash -c "<bash_script.sh>"
    

before_script:
  - docker-compose up -d

script:
  - > 
    docker exec -it recordmarketplace_models_1 bash -c
    "python app/myapp_microservices/manage.py test"

after_script:
  - docker-compose down
