models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./app:/app
    ports:
      - "8001:8000"
    command: bash -c "python /app/myapp_microservices/manage.py makemigrations && python /app/myapp_microservices/manage.py migrate && python /app/myapp_microservices/manage.py loaddata db.json && mod_wsgi-express start-server --working-directory /app/myapp_microservices --reload-on-changes /app/myapp_microservices/myapp_microservices/wsgi.py"

exp:
   image: tp33/django
   links:
      - models:models-api
      - kafka:kafka
   ports:
      - "8002:8000"
   volumes:
      - ./exp:/app
   command: bash -c "mod_wsgi-express start-server --working-directory /app/myapp_exp --reload-on-changes /app/myapp_exp/myapp_exp/wsgi.py"

web:
   image: tp33/django
   links:
      - exp:exp-api
      - es:es
   ports:
      - "8003:8000"
   volumes:
      - ./web:/app
   command: bash -c "mod_wsgi-express start-server --working-directory /app/myapp_web --reload-on-changes /app/myapp_web/myapp_web/wsgi.py"


kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   volumes:
      - ./batch:/batch
   links:
      - kafka:kafka
      - es:es
   command: bash -c "python /batch/kafkaLink.py"
